name: Deploy

runs:
  using: composite
  steps:
    - shell: bash
      run: echo 'The triggering workflow passed'

    - name: 'Download artifact'
      uses: actions/github-script@v7
      with:
        script: |
          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.payload.workflow_run.id,
          });
          let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "run_number"
          })[0];
          let download = await github.rest.actions.downloadArtifact({
            owner: context.repo.owner,
            repo: context.repo.repo,
            artifact_id: matchArtifact.id,
            archive_format: 'zip',
          });
          const fs = require('fs');
          const path = require('path');
          const temp = '${{ runner.temp }}';
          if (!fs.existsSync(temp)){
            fs.mkdirSync(temp);
          }
          fs.writeFileSync(path.join(temp, 'run_number.zip'), Buffer.from(download.data));

    - shell: bash
      run: |
        echo ${{ toJSON(github.event) }}

    - name: 'Unzip artifact'
      shell: bash
      run: |
        unzip ${{ runner.temp }}/run_number.zip -d "${{ runner.temp }}/artifacts"
